name: Patch Checker

on:
    schedule:
        - cron: "*/5 * * * *" # tiap 5 menit
    workflow_dispatch:

jobs:
    run-check:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"

            - name: Install dependencies
              run: pip install feedparser requests

            - name: Run patch checker
              env:
                  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
              run: python check_update.py

            - name: Persist latest.json
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: "update latest"
